global:
  cluster: openshift
  domain: -ctron-drogue.apps.wonderful.iot-playground.org

  partOf: zincati-demo

  drogueCloud:
    jaeger:
      enabled: false

    useServiceCA: true

    keycloak:
      # enable keycloak deployment
      enabled: true
      # enable secure deployment
      insecure: false
      postInstall:
        image: quay.io/keycloak/keycloak:20.0.1

metrics:
  scrapeInterval: 5s

drogueCloudTwin:

  defaults:

    images:
      repository: ghcr.io/drogue-iot
      pullPolicy: IfNotPresent
      tag: 0.1.0

    logging:
      debug: false

  api:
    ingress: {}

  services:

    injector:
      disabled: false
      extraEnvironment:
        - name: INJECTOR__SOURCE__MQTT__HOST
          value: mqtt-integration.sandbox.drogue.cloud
        - name: INJECTOR__SOURCE__MQTT__PORT
          value: "443"
        - name: INJECTOR__SOURCE__MQTT__TOPIC
          value: "$share/mqtt-injector/app/ctron-zincati"
        - name: INJECTOR__METADATA_MAPPER__TYPE
          value: raw
        - name: INJECTOR__METADATA_MAPPER__OVERRIDE_APPLICATION
          value: default
        - name: INJECTOR__PAYLOAD_MAPPER__TYPE
          value: simpleState

    debugger:
      disabled: false

  configuration:
    commands:
      host: mqtt-integration.sandbox.drogue.cloud
      port: 443
      clientId: command-sink
      # username:
      # password:
      disableTls: false
      mapToApplication: ctron-zincati

  kafka:
    kafka:
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 1Gi

  keycloak:
    adminPassword: # see values.secret.yaml

    postInstall:
      user:
        password: # see values.secret.yaml

  postgres:
    password: # see values.secret.yaml

