apiVersion: v1
kind: ConfigMap
metadata:
  name: zincati-scripts
data:
  {{ range $path, $_ :=  .Files.Glob  "scripts/*.js" }}
  {{ base $path }}: |
  {{- $.Files.Get $path | nindent 4 }}
  {{ end }}
